# Homeserver details
homeserver:
    # The address that this appservice can use to connect to the homeserver.
    address: https://matrix.example.com
    # The domain of the homeserver (for MXIDs, etc).
    domain: example.com
    # Whether or not to verify the SSL certificate of the homeserver.
    # Only applies if address starts with https://
    verify_ssl: true

# Application service host/registration related details
# Changing these values requires regeneration of the registration.
appservice:
    # The address that the homeserver can use to connect to this appservice.
    address: http://localhost:29322

    # The hostname and port where this appservice should listen.
    hostname: 0.0.0.0
    port: 29322
    # The maximum body size of appservice API requests (from the homeserver) in mebibytes
    # Usually 1 is enough, but on high-traffic bridges you might need to increase this to avoid 413s
    max_body_size: 1

    # The full URI to the database. SQLite and Postgres are fully supported.
    # Other DBMSes supported by SQLAlchemy may or may not work.
    # Format examples:
    #   SQLite:   sqlite:///filename.db
    #   Postgres: postgres://username:password@hostname/dbname
    database: sqlite:///mautrix-twilio.db

    # The unique ID of this appservice.
    id: twilio
    # Username of the appservice bot.
    bot_username: twiliobot
    # Display name and avatar for bot. Set to "remove" to remove display name/avatar, leave empty
    # to leave display name/avatar as-is.
    bot_displayname: Twilio bridge bot
    bot_avatar: mxc://maunium.net/FYuKJHaCrSeSpvBJfHwgYylP

    # Community ID for bridged users (changes registration file) and rooms.
    # Must be created manually.
    community_id: null

    # Authentication tokens for AS <-> HS communication. Autogenerated; do not modify.
    as_token: "This value is generated when generating the registration"
    hs_token: "This value is generated when generating the registration"

# Bridge config
bridge:
    # Localpart template of MXIDs for remote users.
    # {userid} is replaced with the phone number of the user (international format without +).
    username_template: "twilio_whatsapp_{userid}"
    # Displayname template for remote users.
    # {displayname} is replaced with the phone number of the user (international format without +).
    displayname_template: "+{displayname} (WhatsApp)"

    # The prefix for commands. Only required in non-management rooms.
    command_prefix: "!tw"

    # Whether or not created rooms should have federation enabled.
    # If false, created portal rooms will never be federated.
    federate_rooms: true
    # Initial room state for created rooms.
    initial_state:
        m.room.power_levels:
            events_default: 0
            users_default: 0
            state_default: 50
            events:
                m.room.avatar: 0
                m.room.name: 0
                m.room.topic: 0

    # Permissions for using the bridge.
    # Permitted values:
    #       user - Use the bridge with puppeting.
    #      admin - Use and administrate the bridge.
    # Permitted keys:
    #        * - All Matrix users
    #   domain - All users on that homeserver
    #     mxid - Specific user
    permissions:
        "example.com": "user"
        "@admin:example.com": "admin"

# Twilio webhook settings.
twilio:
    # Twilio account ID
    account_id: AC1082dcd0e9ae51404f6cae3581edfbff
    # Twilio phone number to send messages from.
    sender_id: whatsapp:+1415550199
    # Your Twilio auth token (get from Twilio dashboard front page)
    secret: 2035141f21a001604e763c009aa3be4c
    # Path prefix for webhook endpoints. Subpaths are /status and /receive.
    # Note that the webhook must be put behind a reverse proxy with https.
    webhook_path: /twilio

# Python logging configuration.
#
# See section 16.7.2 of the Python documentation for more info:
# https://docs.python.org/3.7/library/logging.config.html#configuration-dictionary-schema
logging:
    version: 1
    formatters:
        colored:
            (): mautrix.util.color_log.ColorFormatter
            format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
        normal:
            format: "[%(asctime)s] [%(levelname)s@%(name)s] %(message)s"
    handlers:
        file:
            class: logging.handlers.RotatingFileHandler
            formatter: normal
            filename: ./mautrix-twilio.log
            maxBytes: 10485760
            backupCount: 10
        console:
            class: logging.StreamHandler
            formatter: colored
    loggers:
        mau:
            level: DEBUG
        fbchat:
            level: DEBUG
        aiohttp:
            level: INFO
    root:
        level: DEBUG
        handlers: [file, console]
